/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as PlaylistsPlaylistIdRouteImport } from './routes/playlists/$playlistId'
import { Route as ArtistsArtistKeyRouteImport } from './routes/artists/$artistKey'
import { Route as AlbumsAlbumKeyRouteImport } from './routes/albums/$albumKey'
import { Route as ExploreRecommendationsRecIdRouteImport } from './routes/explore/recommendations/$recId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlaylistIdRoute = PlaylistsPlaylistIdRouteImport.update({
  id: '/playlists/$playlistId',
  path: '/playlists/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtistKeyRoute = ArtistsArtistKeyRouteImport.update({
  id: '/artists/$artistKey',
  path: '/artists/$artistKey',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumKeyRoute = AlbumsAlbumKeyRouteImport.update({
  id: '/albums/$albumKey',
  path: '/albums/$albumKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRecommendationsRecIdRoute =
  ExploreRecommendationsRecIdRouteImport.update({
    id: '/explore/recommendations/$recId',
    path: '/explore/recommendations/$recId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums/$albumKey': typeof AlbumsAlbumKeyRoute
  '/artists/$artistKey': typeof ArtistsArtistKeyRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/explore/': typeof ExploreIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/explore/recommendations/$recId': typeof ExploreRecommendationsRecIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albums/$albumKey': typeof AlbumsAlbumKeyRoute
  '/artists/$artistKey': typeof ArtistsArtistKeyRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/explore': typeof ExploreIndexRoute
  '/library': typeof LibraryIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/explore/recommendations/$recId': typeof ExploreRecommendationsRecIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/albums/$albumKey': typeof AlbumsAlbumKeyRoute
  '/artists/$artistKey': typeof ArtistsArtistKeyRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/explore/': typeof ExploreIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/explore/recommendations/$recId': typeof ExploreRecommendationsRecIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums/$albumKey'
    | '/artists/$artistKey'
    | '/playlists/$playlistId'
    | '/explore/'
    | '/library/'
    | '/onboarding/'
    | '/playlists/'
    | '/settings/'
    | '/explore/recommendations/$recId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albums/$albumKey'
    | '/artists/$artistKey'
    | '/playlists/$playlistId'
    | '/explore'
    | '/library'
    | '/onboarding'
    | '/playlists'
    | '/settings'
    | '/explore/recommendations/$recId'
  id:
    | '__root__'
    | '/'
    | '/albums/$albumKey'
    | '/artists/$artistKey'
    | '/playlists/$playlistId'
    | '/explore/'
    | '/library/'
    | '/onboarding/'
    | '/playlists/'
    | '/settings/'
    | '/explore/recommendations/$recId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsAlbumKeyRoute: typeof AlbumsAlbumKeyRoute
  ArtistsArtistKeyRoute: typeof ArtistsArtistKeyRoute
  PlaylistsPlaylistIdRoute: typeof PlaylistsPlaylistIdRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ExploreRecommendationsRecIdRoute: typeof ExploreRecommendationsRecIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$playlistId': {
      id: '/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$artistKey': {
      id: '/artists/$artistKey'
      path: '/artists/$artistKey'
      fullPath: '/artists/$artistKey'
      preLoaderRoute: typeof ArtistsArtistKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumKey': {
      id: '/albums/$albumKey'
      path: '/albums/$albumKey'
      fullPath: '/albums/$albumKey'
      preLoaderRoute: typeof AlbumsAlbumKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/recommendations/$recId': {
      id: '/explore/recommendations/$recId'
      path: '/explore/recommendations/$recId'
      fullPath: '/explore/recommendations/$recId'
      preLoaderRoute: typeof ExploreRecommendationsRecIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsAlbumKeyRoute: AlbumsAlbumKeyRoute,
  ArtistsArtistKeyRoute: ArtistsArtistKeyRoute,
  PlaylistsPlaylistIdRoute: PlaylistsPlaylistIdRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ExploreRecommendationsRecIdRoute: ExploreRecommendationsRecIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
